### ISSUE TITLE
Show users who are in several groups in the respective groups

### ISSUE THREAD

**Issue by TheChaosToast** [RLNT/sinus-staff-list#10]
### Feature Description

Users who are in several groups are also shown in the respective groups
### Additional Context

Hello everybody,

if I have a user, this is only displayed in a group. Is it possible to display this one user in the other groups?

Example: The User Admin is a member of the Admin, Developer and Supporter group. If I set this up, this user will only be displayed in one of the 3 server groups (in this case developer). Can you stop that?

Thanks a lot :)

**Comment by DAmNRelentless** [comment]
Since you submitted this as a question, I will simply answer you.

The current build of the script does not support showing users in multiple groups. A user is only shown in the group with the highest priority which is the last group you defined in the config.

However you could request this as a feature by submitting a feature request on the issue tab. Don't make it a question and I will take a look whether I'll implement it in the next version.
