### ISSUE TITLE
Staff List

### ISSUE THREAD

**Issue by Acu1ty** [RLNT/sinus-staff-list#34]
Hello i have suggest that will improve script i wanna suggest for variable something like how many users is inside group, variable to display channel in which the user is located, variable for icons example add here new text box http://prntscr.com/ufrc2t and when user insert icon, you can use for example variable %icon-group% to display group icon i made example http://prntscr.com/ufrcpk

**Comment by DAmNRelentless** [comment]
While the screenshot itself looks like a pretty cool design, there are some issues with your feature request.

First of all, it is not possible for us to get all clients from a servergroup with the SinusBot API. Therefor we use a custom database for the script which registers each relevant client of the staff groups you set up.
If you want to keep track of the amount of clients that belongs to a specific staff group, we also had to store this information and then, you have the problem that everyone who has to be counted towards that group, needs to be online once again after the update was installed.

Second, displaying the channel of a client is pretty performance draining since there is no way of getting the current channel of a client just by their uid or username. You would first have to get the client object from the teamspeak server and then you would have to search on the whole server in which channel this specific client is.
While that is a pretty heave step performance wise already, you have to keep in mind that you would have to do this for every relevant client and you would have to update this information whenever someone switches channels.
Not to forget what happens when the channel the client joined into is not visible to the bot.

So in general, it's not only very performance draining, it is also pretty complicated to implement.
If there are proper API calls in the future who support this, we will implement these features but right now, it just makes no sense.
