### ISSUE TITLE
Need more Option

### ISSUE THREAD

**Issue by zockparadies** [RLNT/sinus-staff-list#8]
Hello, thanks for this awesome Script! Hope you can work on my needed Features ^^

## Feature Description ##

Please add a Option to show more Groups in one Description
And a Option to show the Online Status in the Channel Name. 
### Additional Context (EXAMPLE)

<a href="https://ibb.co/XX3P1Tj"><img src="https://i.ibb.co/XX3P1Tj/example.png" alt="example" border="0"></a> <a href="https://ibb.co/f0ypTdt"><img src="https://i.ibb.co/f0ypTdt/example2.png" alt="example2" border="0"></a>

**Comment by VeLutI0n** [comment]
You can enter a lot of groups in the channel. Only one person may not have both groups, since they can only be shown in one. Even if there are 2 channels

**Comment by DAmNRelentless** [comment]
Well, you would have to be a bit more specific. I can't just look into your head on what you mean with your suggestions.

"Please add a Option to show more Groups in one Description"
The staff list already shows multiple groups in one description. You just need to add them in the config. You can set up as many groups as you want to show up in the description.
If that's not what you meant, you have to be more specific.

"And a Option to show the Online Status in the Channel Name."
The online status for who? It's a list. How would you configure the user of which the status is shown? Because it is a list, it's the best idea to show it in the description.
You need to be more specific on what you mean and don't just expect that I can read your mind.

**Comment by TheChaosToast** [comment]
Hello everybody,

could one insert in the script that unused groups can write a freely definable text? At the moment it is so that groups that are not used are not shown in the list. If these groups are still displayed but you can insert your own text there, that would be really good :)

**Comment by DAmNRelentless** [comment]
@TheChaosToast That's actually a good idea. But please submit this in an own feature request.
